import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Anton } from "next/font/google";

import "./globals.css";

import { Providers } from "./Provider";

const Libertinus = Anton({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={` relative     antialiased`}>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
